import React, { useState } from 'react';
import CustomDropdown from './custom_dropdown';
import { View, StyleSheet, Text } from 'react-native';

const defaultNationalities = [
  { label: 'Afegão', value: 1 },
  { label: 'Albanês', value: 2 },
  { label: 'Alemão', value: 3 },
  { label: 'Andorrano', value: 4 },
  { label: 'Angolano', value: 5 },
  { label: 'Antiguano', value: 6 },
  { label: 'Árabe', value: 7 },
  { label: 'Argentino', value: 8 },
  { label: 'Armênio', value: 9 },
  { label: 'Australiano', value: 10 },
  { label: 'Austríaco', value: 11 },
  { label: 'Azerbaijano', value: 12 },
  { label: 'Bahamense', value: 13 },
  { label: 'Bahreinita', value: 14 },
  { label: 'Bangladeshiano', value: 15 },
  { label: 'Barbadiano', value: 16 },
  { label: 'Belga', value: 17 },
  { label: 'Belizenho', value: 18 },
  { label: 'Beninense', value: 19 },
  { label: 'Bielorrusso', value: 20 },
  { label: 'Birmanês', value: 21 },
  { label: 'Boliviano', value: 22 },
  { label: 'Bósnio', value: 23 },
  { label: 'Botsuano', value: 24 },
  { label: 'Brasileiro', value: 25 },
  { label: 'Bruneano', value: 26 },
  { label: 'Búlgaro', value: 27 },
  { label: 'Burquinês', value: 28 },
  { label: 'Burundiano', value: 29 },
  { label: 'Cabo-Verdiano', value: 30 },
  { label: 'Camaronês', value: 31 },
  { label: 'Canadense', value: 32 },
  { label: 'Catarense', value: 33 },
  { label: 'Chinês', value: 34 },
  { label: 'Cipriota', value: 35 },
  { label: 'Comorense', value: 36 },
  { label: 'Congolês', value: 37 },
  { label: 'Coreano do Norte', value: 38 },
  { label: 'Coreano do Sul', value: 39 },
  { label: 'Costa-Marfinense', value: 40 },
  { label: 'Costarriquenho', value: 41 },
  { label: 'Croata', value: 42 },
  { label: 'Cubano', value: 43 },
  { label: 'Dinamarquês', value: 44 },
  { label: 'Dominicano', value: 45 },
  { label: 'Egípcio', value: 46 },
  { label: 'Emiratense', value: 48 },
  { label: 'Equatoriano', value: 49 },
  { label: 'Eritreu', value: 50 },
  { label: 'Eslovaco', value: 51 },
  { label: 'Esloveno', value: 52 },
  { label: 'Espanhol', value: 53 },
  { label: 'Estoniano', value: 54 },
  { label: 'Eswatini', value: 55 },
  { label: 'Etíope', value: 56 },
  { label: 'Fijiano', value: 57 },
  { label: 'Filipino', value: 58 },
  { label: 'Finlandês', value: 59 },
  { label: 'Gabonês', value: 60 },
  { label: 'Gambiano', value: 61 },
  { label: 'Georgiano', value: 62 },
  { label: 'Granadino', value: 63 },
  { label: 'Grego', value: 64 },
  { label: 'Guatemalteco', value: 65 },
  { label: 'Guineano', value: 66 },
  { label: 'Guineense', value: 67 },
  { label: 'Guineu-equatoriano', value: 68 },
  { label: 'Haitiano', value: 69 },
  { label: 'Hondurenho', value: 70 },
  { label: 'Húngaro', value: 71 },
  { label: 'Iemenita', value: 72 },
  { label: 'Indiano', value: 73 },
  { label: 'Indonésio', value: 74 },
  { label: 'Iraniano', value: 75 },
  { label: 'Iraquiano', value: 76 },
  { label: 'Irlandês', value: 77 },
  { label: 'Islandês', value: 78 },
  { label: 'Israelense', value: 79 },
  { label: 'Italiano', value: 80 },
  { label: 'Jamaicano', value: 81 },
  { label: 'Japonês', value: 82 },
  { label: 'Jordano', value: 83 },
  { label: 'Kiribatiano', value: 84 },
  { label: 'Kuwaitiano', value: 85 },
  { label: 'Laociano', value: 86 },
  { label: 'Lesoto', value: 87 },
  { label: 'Letão', value: 88 },
  { label: 'Libanês', value: 89 },
  { label: 'Liberiano', value: 90 },
  { label: 'Líbio', value: 91 },
  { label: 'Lituano', value: 92 },
  { label: 'Luxemburguês', value: 93 },
  { label: 'Macedônio', value: 94 },
  { label: 'Malásio', value: 95 },
  { label: 'Malauiano', value: 96 },
  { label: 'Maldivo', value: 97 },
  { label: 'Maliano', value: 98 },
  { label: 'Maltês', value: 99 },
  { label: 'Marroquino', value: 100 },
  { label: 'Mauriciano', value: 101 },
  { label: 'Mauritano', value: 102 },
  { label: 'Mexicano', value: 103 },
  { label: 'Micronésio', value: 104 },
  { label: 'Moçambicano', value: 109 },
  { label: 'Moldavo', value: 105 },
  { label: 'Monegasco', value: 106 },
  { label: 'Mongol', value: 107 },
  { label: 'Montenegrino', value: 108 },
  { label: 'Namibiano', value: 110 },
  { label: 'Nauruano', value: 111 },
  { label: 'Neozelandês', value: 113 },
  { label: 'Nepalês', value: 112 },
  { label: 'Nigeriano', value: 114 },
  { label: 'Nigerino', value: 115 },
  { label: 'Norueguês', value: 116 },
  { label: 'Omani', value: 117 },
  { label: 'Palauense', value: 118 },
  { label: 'Panamenho', value: 119 },
  { label: 'Papua', value: 120 },
  { label: 'Paquistanês', value: 121 },
  { label: 'Paraguaio', value: 122 },
  { label: 'Peruano', value: 123 },
  { label: 'Polaco', value: 124 },
  { label: 'Português', value: 125 },
  { label: 'Queniano', value: 126 },
  { label: 'Quirguiz', value: 127 },
  { label: 'Romeno', value: 129 },
  { label: 'Ruandês', value: 128 },
  { label: 'Russo', value: 130 },
  { label: 'Salomonense', value: 131 },
  { label: 'Salvadorenho', value: 47 },
  { label: 'Samoano', value: 132 },
  { label: 'São-tomense', value: 133 },
  { label: 'São-vicentino', value: 134 },
  { label: 'Senegalês', value: 135 },
  { label: 'Serra-leonino', value: 136 },
  { label: 'Sérvio', value: 137 },
  { label: 'Seychelense', value: 138 },
  { label: 'Sírio', value: 139 },
  { label: 'Somali', value: 140 },
  { label: 'Sueco', value: 145 },
  { label: 'Suíço', value: 146 },
  { label: 'Sul-africano', value: 141 },
  { label: 'Sul-coreano', value: 142 },
  { label: 'Sul-sudanês', value: 143 },
  { label: 'Surinamês', value: 144 },
  { label: 'Tailandês', value: 149 },
  { label: 'Tajique', value: 147 },
  { label: 'Tanzaniano', value: 148 },
  { label: 'Timorense', value: 150 },
  { label: 'Togolês', value: 151 },
  { label: 'Tonganês', value: 152 },
  { label: 'Trinitário', value: 153 },
  { label: 'Tunisiano', value: 154 },
  { label: 'Turco', value: 155 },
  { label: 'Turcomeno', value: 156 },
  { label: 'Tuvaluano', value: 157 },
  { label: 'Ucraniano', value: 158 },
  { label: 'Ugandense', value: 159 },
  { label: 'Uruguaio', value: 160 },
  { label: 'Uzbeque', value: 161 },
  { label: 'Vanuatuense', value: 162 },
  { label: 'Venezuelano', value: 163 },
  { label: 'Vietnamita', value: 164 },
  { label: 'Zambiano', value: 165 },
  { label: 'Zimbabuano', value: 166 }
];

const NationalityDropdown = ({ value, onSelect, error }) => {

  const [nationalities] = useState(defaultNationalities);
  const selectedOption = nationalities.find(option => option.value === value) || null;

  return (
    <View>
      <CustomDropdown
        placeholder="Nacionalidade"
        options={nationalities}
        value={selectedOption}
        onSelect={onSelect}
        error={error}
      />
      {error && <Text style={styles.errorMessage}>{error}</Text>}
    </View>
  );
};

const styles = StyleSheet.create({
  errorMessage: {
    color: '#ff4444',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 5,
  }
});

export default NationalityDropdown;